import type { Lang } from "./types";

export const dict = {
  th: {
    navHome: "หน้าแรก",
    navGallery: "ผลงาน",
    navBook: "จองคิว",
    hero: "ตัดผมชาย หัวหิน",
    sub: "จองคิวออนไลน์ ไม่ต้องรอนาน",
    ctaPrimary: "จองคิวเลย",
    ctaSecondary: "ดูผลงาน",
    ctaTertiary: "เลือกบริการ",
    hours: "เปิดทุกวัน 08:00–21:00 น.",
    labelName: "ชื่อ",
    placeholderName: "สมชาย",
    labelPhone: "เบอร์โทร",
    placeholderPhone: "081-234-5678",
    labelService: "บริการ",
    labelDate: "วัน",
    labelTime: "เวลา",
    labelNotes: "หมายเหตุ (ไม่บังคับ)",
    placeholderNotes: "เช่น ช่างประจำ / ทรงที่อยากได้",
    submit: "ยืนยันจองคิว",
    success: "จองคิวสำเร็จแล้ว ร้านจะโทรยืนยันนะครับ",
    adminTitle: "คิววันนี้",
    adminLogin: "เข้าสู่ระบบ",
    labelPassword: "รหัสผ่าน",
    minutes: "นาที",
    pdpa: "ร้านใช้ชื่อและเบอร์โทรเพื่อยืนยันนัดและติดต่อเรื่องคิวเท่านั้น ไม่ใช้เพื่อโฆษณา หากไม่ให้ข้อมูลจะจองคิวไม่ได้ ท่านมีสิทธิขอเข้าถึง แก้ไข หรือลบข้อมูลได้โดยติดต่อร้าน",
    lateLine: "สาย 10 นาที ปล่อยคิว",
    langTh: "TH",
    langEn: "EN",
    contactPhone: "โทร",
    contactEmail: "อีเมล",
    contactAddress: "ที่อยู่",
    contactDirections: "เส้นทาง",
    back: "ย้อนกลับ",
    backHome: "กลับหน้าแรก",
    reviewsTitle: "รีวิวลูกค้า",
    reviewsSoon: "รีวิวจากลูกค้าจริง มาเร็วๆ นี้",
    reviewsFromGoogle: "เชื่อมต่อรีวิว Google ได้ภายหลัง",
    reviewsAdd: "เพิ่มรีวิว",
    reviewsDelete: "ลบ",
    labelStars: "ดาว",
    labelQuoteTh: "ข้อความไทย",
    labelQuoteEn: "ข้อความอังกฤษ",
    slotTaken: "เต็ม",
    adminCancel: "ยกเลิกคิว",
    adminEmpty: "ยังไม่มีคิว",
  },
  en: {
    navHome: "Home",
    navGallery: "Gallery",
    navBook: "Book",
    hero: "Men's cuts in Hua Hin",
    sub: "Book online, skip the wait.",
    ctaPrimary: "Book now",
    ctaSecondary: "See our work",
    ctaTertiary: "Services",
    hours: "Open daily 08:00–21:00",
    labelName: "Name",
    placeholderName: "Somchai",
    labelPhone: "Phone",
    placeholderPhone: "081-234-5678",
    labelService: "Service",
    labelDate: "Date",
    labelTime: "Time",
    labelNotes: "Notes (optional)",
    placeholderNotes: "Regular barber / style notes",
    submit: "Confirm booking",
    success: "You're booked. We'll call to confirm.",
    adminTitle: "Today's bookings",
    adminLogin: "Log in",
    labelPassword: "Password",
    minutes: "min",
    pdpa: "We use your name and phone only to confirm this booking and contact you about your slot. We do not send ads. If you skip these fields we cannot book you; contact the shop to access, correct, or delete your data.",
    lateLine: "10 min late — slot released",
    langTh: "TH",
    langEn: "EN",
    contactPhone: "Phone",
    contactEmail: "Email",
    contactAddress: "Address",
    contactDirections: "Directions",
    back: "Back",
    backHome: "Back to home",
    reviewsTitle: "Customer reviews",
    reviewsSoon: "Real customer reviews coming soon.",
    reviewsFromGoogle: "Google reviews can be connected later.",
    reviewsAdd: "Add review",
    reviewsDelete: "Delete",
    labelStars: "Stars",
    labelQuoteTh: "Quote (Thai)",
    labelQuoteEn: "Quote (English)",
    slotTaken: "Booked",
    adminCancel: "Cancel",
    adminEmpty: "No bookings yet",
  },
} as const;

export type DictKey = keyof typeof dict.th;

export function t(lang: Lang, key: DictKey): string {
  return dict[lang][key];
}
